### PR TITLE
fix: add `x-terminal:focus` command to atom-workspace

### LINKED ISSUE #178: [BR] Terminal Focus doesn't create new window
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Description

@UziTech I see your test in the PR that should cover this case, so I'm not sure how this behavior is happening. But, after doing all the normal restarting/refreshing/reinstalling calling terminal focus still doesn't create a new window for me.

### Steps to reproduce
1. Open A Folder/Project
2. Call the terminal-focus command with a keybind

**Expected behavior:**
New x-terminal window 

**Actual behavior:**
If I call terminal-open it'll open up a new terminal in the bottom panel, but terminal-focus does nothing. (I have no other terminals open in any other pane). Errors in the console are a different extension (no errors from x-terminal).
Screen Shot 2020-10-07 at 10 11 48 AM

**Reproduces how often:**
100%

### Versions
`Atom    : 1.50.0`

OS name and version: Mac Sierra 
Terminal version: 10.0.1

### PR DESCRIPTION
**Pull request by UziTech**
fixes #178

### CODE REVIEW

**Review by the-j0k3r — APPROVED** [review]

File: src/element.js [hunk 1]
```diff
@@ -704,10 +704,14 @@ class XTerminalElementImpl extends HTMLElement {
...
 
-	focusOnTerminal () {
+	focusOnTerminal (double) {
 		if (this.terminal) {
 			this.model.setActive()
 			this.terminal.focus()
+			if (double) {
+				// second focus with send command to pty
+				this.terminal.focus()
+			}
```
Comment (UziTech) [inline src/element.js]: for some reason calling focus on xterm does not focus the pty unless it is called twice.
